[github_app]
pr_commands = ["/agentic_review"]
feedback_or_draft_pr = false
handle_push_trigger = true
push_commands = ["/agentic_review"]

[auto_best_practices]
enable_auto_best_practices = true
utilize_auto_best_practices = true

[review_agent]
enabled = true
publish_output = true
comments_location_policy = "summary"
final_update_message = false
persistent_comment = true
persistent_comment_notification = false

[checks]
enable_auto_checks_feedback = false

[config]
publish_output_progress = false
