name: tests-windows

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: number

jobs:
  better-sqlite3:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-node
        with:
          node-version: ${{ inputs.node-version }}
          download-build: true

      - run: jq 'map(select(.type == "better-sqlite3"))' ormconfig.sample.json > ormconfig.json
      - run: pnpm exec c8 pnpm run test:ci

      - uses: coverallsapp/github-action@v2
        with:
          flag-name: better-sqlite3-node:${{ inputs.node-version }}-windows
          parallel: true

  sqljs:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-node
        with:
          node-version: ${{ inputs.node-version }}
          download-build: true

      - run: jq 'map(select(.type == "sqljs"))' ormconfig.sample.json > ormconfig.json
      - run: pnpm exec c8 pnpm run test:ci

      - uses: coverallsapp/github-action@v2
        with:
          flag-name: sqljs-node:${{ inputs.node-version }}-windows
          parallel: true
